version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./producer-converter/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always
    networks:
      - resolute

  redis-cache:
    container_name: redis-cache
    hostname: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - resolute

  producer:
    build: ./producer-converter
    container_name: producer-converter
    image: producer-converter
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - redis-cache
    links:
      - rabbitmq
      - redis-cache
    networks:
      - resolute

networks:
  resolute:
    external:
      name: resolute