name: Test Get Actions GitHub API

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - test-actions-api

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Testando Aplicação
        env:
          ACTION: ${{ github.event.client_payload.action }}
          TENANT: ${{ github.event.client_payload.alias }}
          VAR: ${{github.testando_var}}
        run: echo $ACTION ; echo $TENANT ; echo $VAR
        
