name: Test Get Actions GitHub API

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      - test-actions-api

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Testando Aplicação
      - env:
          VAR: ${{ github.event.client_payload.varTest }}
          MSG: ${{ github.event.client_payload.msg }}
        run: echo Actions via API deu bom! | echo $VAR | echo $MSG
        
